server:
  port: 10089
spring:
  redis:
    host: 114.215.186.226
    port: 6379
    timeout: 3000
  mail:
    host: smtp.qq.com #发送邮件服务器 (smtp.126.com为162，163，yeah邮箱)
    default-encoding: UTF-8
    username: tydyiu@qq.com
    password: #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    from: tydyiu@qq.com
    properties.mail.smtp.port: 465 #端口号465或587
    #126邮箱SMTP服务器地址:smtp.126.com,端口号:465或者994
    #163邮箱SMTP服务器地址:smtp.163.com,端口号:465或者994
    #yeah邮箱SMTP服务器地址:smtp.yeah.net,端口号:465或者994
