server:
  port: 10090
spring:
  application:
    name: nanophase-security
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
      config:
        server-addr: http://localhost:8848/
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 114.215.186.226
    # redis端口（默认为6379）
    port: 6379
    # redis连接超时时间（单位毫秒）
    timeout: 3000