server:
  port: 10090
spring:
  application:
    name: nanophase-security
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
      config:
        server-addr: http://localhost:8848/